### ISSUE TITLE
not working imports

### ISSUE THREAD

**Issue by acopalipsis** [aikoven/typed-material-ui#4]
> npm i --save-dev @types/material-ui

package.json 

> "@types/material-ui": "^0.16.50",
> "@types/react": "^15.0.7",
> "react": "^15.4.2",

```
import Menu from "material-ui/Menu";

console.log( Menu )// function Menu(){...}
```

```
import DropDownMenu from "material-ui/DropDownMenu";

console.log( DropDownMenu ) // Module not found: Error: Can't resolve 'material-ui/DropDownMenu' in ...
```

And a lot of the components are not imported with the same error.

**Comment by aikoven** [comment]
This repo is not the same as `@types/material-ui`, which resides at https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/material-ui.

You should use `npm i typed-material-ui` to install these. See usage guide in [README](https://github.com/aikoven/typed-material-ui/blob/master/README.md).
